# use Ganache's forked mainnet mode as the default network
networks:
  default: development

autofetch_sources: true

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0

compiler:
  solc:
    version: 0.8.12
    remappings:
      - "@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.5.0/contracts"
      - "ds-test/=lib/ds-test/src/"
      - "forge-std/=lib/forge-std/src/"

reports:
  exclude_contracts:
    - SafeERC20
    - Address
    - Token